name: codecov

on: [push, pull_request]

jobs:
  run:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ 1.21.x ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Generate Coverage Report
      run: go test ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Upload Coverage Report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
